# Set baseline image
FROM pytorch/pytorch:2.1.1-cuda12.1-cudnn8-devel

# Set the working directory
WORKDIR <YOUR_WORKING_DIR>

ENV DEBIAN_FRONTEND=noninteractive

COPY requirements.txt <YOUR_WORKING_DIR>

RUN python3 -m pip install --no-cache-dir --upgrade --pre pip
RUN python3 -m pip install --no-cache-dir -r requirements.txt